language: java

jdk:
  - oraclejdk8
  
sudo: false

services:
  - docker

before_install:
- cd docker/dev
- docker-compose up -d

before_script:
- cd ../../src
  
  
script:
  - mvn --file ./pom.xml clean install -P test-consumer,test-business
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -v
  - Y
  - docker-compose up -d
  - cd ../../src
after_success:
  - mvn --file ./src/pom.xml cobertura:cobertura -P test-consumer,test-business
  
notifications:
email: false