language: java

jdk:
  - oraclejdk8
  
sudo: false

services:
  - docker

before_install:
- cd docker/dev
- docker-compose up -d
- cd ../../src
  
script:
  - mvn --file ./pom.xml clean install -P test-consumer,test-business

after_success:
  - mvn --file pom.xml cobertura:cobertura coveralls:report -P test-consumer,test-business
  
notifications:
email: false