language: java
jdk:
  - oraclejdk8
sudo: false
services:
  - docker
before_script:
  - docker-compose -f docker/dev/docker-compose.yml up -d
script:
  - mvn --file ./src/pom.xml clean jacoco:prepare-agent install jacoco:report coveralls:report -P test-consumer,test-business
after_script:
  - cd src
  - mvn clean install jacoco:report coveralls:report
  - docker-compose -f docker/dev/docker-compose.yml stop
  - docker-compose -f docker/dev/docker-compose.yml rm -f